---
name: pipeline
on:
  push:
    branches:
      - main
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: check Base image
        run: |
          DOCKERFILE=$(find . -iname 'dockerfile')
          if [ -f "${DOCKERFILE}" ]; then
            echo Dockerfile found at $(pwd)/"${DOCKERFILE}"
            DOCKERFILE_BASE_IMAGE=$(grep -Ei '^FROM\s+' $DOCKERFILE | awk '{print $2}');
            if grep -q $DOCKERFILE_BASE_IMAGE allowedImages.txt; then
              echo "Your Dockerfile Base Images are allowed. Continuing pipeline.";
            else
              echo "ERROR: Your Dockerfile Base images are not allowed. Aborting pipeline.";
              echo -e '\n'"Please Review your Dockerfile and replace base images from the Approved Images Registries.";
              exit 1;
            fi
          else
            echo "Dockerfile not found."
          fi
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: |
          docker build .

